export const FETCH_TRAVELS_START = 'FETCH_TRAVELS_START'
export const FETCH_TRAVELS_SUCCESS = 'FETCH_TRAVELS_SUCCESS'
export const FETCH_TRAVELS_ERROR = 'FETCH_TRAVELS_ERROR'

export const FETCH_MAX_INPUT = 'FETCH_MAX_INPUT'
export const FETCH_MIN_INPUT = 'FETCH_MIN_INPUT'

export const FETCH_ONE_TRANSFER = 'FETCH_ONE_TRANSFER'
export const FETCH_ZERO_TRANSFER = 'FETCH_ZERO_TRANSFER'

export const FETCH_COMPANY = 'FETCH_COMPANY'

export const FETCH_FOR_ENCREMENT = 'FETCH_FOR_ENCREMENT'
export const FETCH_FOR_DECREMENT = 'FETCH_FOR_DECREMENT'
export const FETCH_FOR_TIME = 'FETCH_FOR_TIME'

export const FETCH_AVIA = 'FETCH_AVIA'
